/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wcripper;

import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class WCFrame extends javax.swing.JFrame {

    /**
     * Creates new form WCFrame
     */
    public WCFrame() {
        initComponents();
        setTitle("WCRipper - No more WannaCry 2.0!");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("WannaCrypt.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txOut = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName(""); // NOI18N

        jButton1.setText("Vaccine computer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txOut.setColumns(20);
        txOut.setRows(5);
        jScrollPane1.setViewportView(txOut);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wcripper/WannaCrypt.jpg"))); // NOI18N

        jButton2.setText("Credits");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("WCRipper - No more Wanna Cry 2.0!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String command = "powershell.exe RunAs new-netfirewallrule -displayname Mtest -direction outbound -action block -protocol tcp -RemotePort 135";
            String command2 = "powershell.exe RunAs new-netfirewallrule -displayname Mtest -direction outbound -action block -protocol tcp -RemotePort 136";
            String command3 = "powershell.exe RunAs new-netfirewallrule -displayname Mtest -direction outbound -action block -protocol tcp -RemotePort 137";
            String command4 = "powershell.exe RunAs new-netfirewallrule -displayname Mtest -direction outbound -action block -protocol tcp -RemotePort 138";
            String command5 = "powershell.exe RunAs new-netfirewallrule -displayname Mtest -direction outbound -action block -protocol tcp -RemotePort 139";
            String command6 = "powershell.exe RunAs new-netfirewallrule -displayname Mtest -direction outbound -action block -protocol tcp -RemotePort 445";
            String command7 = "powershell.exe RunAs Disable-WindowsOptionalFeature -Online -FeatureName smb1protocol";
            
        VaccinePC cure = new VaccinePC();
        txOut.setText(txOut.getText()+"Performing firewall block on WC2_P1\n");
        cure.ExecCure(command);
        txOut.setText(txOut.getText()+"STATUS: DONE\n");
        txOut.setText(txOut.getText()+"Performing firewall block on WC2_P2\n");
        cure.ExecCure(command2);
        txOut.setText(txOut.getText()+"STATUS: DONE\n");
        txOut.setText(txOut.getText()+"Performing firewall block on WC2_P3\n");
        cure.ExecCure(command3);
        txOut.setText(txOut.getText()+"STATUS: DONE\n");
        txOut.setText(txOut.getText()+"Performing firewall block on WC2_P4\n");
        cure.ExecCure(command4);
        txOut.setText(txOut.getText()+"STATUS: DONE\n");
        txOut.setText(txOut.getText()+"Performing firewall block on WC2_P5\n");
        cure.ExecCure(command5);
        txOut.setText(txOut.getText()+"STATUS: DONE\n");
        txOut.setText(txOut.getText()+"Performing firewall block on WC2_P6\n");
        cure.ExecCure(command6);
        txOut.setText(txOut.getText()+"STATUS: DONE\n");
        txOut.setText(txOut.getText()+"Disabling WC2_FLAW_PROTOCOL\n");
        cure.ExecCure(command7);
        txOut.setText(txOut.getText()+"STATUS: ALL DONE\n");
        txOut.setText(txOut.getText()+"WannaCry 2.0 has been blocked for this computer!\n\n");
        txOut.setText(txOut.getText()+"WCRipper - No more WannaCry 2.0\n");

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String credits ="THIS PROGRAM IS FREEWARE! IF YOU PAID FOR IT,\n ASK FOR THE MONEY BACK! "
                + "THIS PROGRAM IS PREPARED TO STOP \nWANNACRY 2.0 FROM SPREADING INTO YOUR COMPUTER\n"
                + "AND FROM USING YOUR COMPUTER TO SPREAD IT SELF\n INTO A NETWORK\n"
                + "ALL CREDITS TO: phtom \n"
                + "CONTACT EMAIL: ******************\n"
                + "PROGRAM VERSION: v1.0";
        txOut.setText(credits);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WCFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txOut;
    // End of variables declaration//GEN-END:variables
}
